# The set of CRDs used by machine-controller-manager
#
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: machineclasses.machine.sapcloud.io
spec:
  conversion:
    strategy: None
  group: machine.sapcloud.io
  names:
    kind: MachineClass
    listKind: MachineClassList
    plural: machineclasses
    shortNames:
      - machcls
    singular: machineclass
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}

---

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: awsmachineclasses.machine.sapcloud.io
spec:
  conversion:
    strategy: None
  group: machine.sapcloud.io
  names:
    kind: AWSMachineClass
    listKind: AWSMachineClassList
    plural: awsmachineclasses
    shortNames:
    - awscls
    singular: awsmachineclass
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.machineType
      name: Machine Type
      type: string
    - jsonPath: .spec.ami
      name: AMI
      type: string
    - jsonPath: .spec.region
      name: Region
      priority: 1
      type: string
    - description: |-
        CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.
        Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
      jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: machines.machine.sapcloud.io
spec:
  conversion:
    strategy: None
  group: machine.sapcloud.io
  names:
    kind: Machine
    listKind: MachineList
    plural: machines
    shortNames:
      - mach
    singular: machine
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - description: Current status of the machine.
          jsonPath: .status.currentStatus.phase
          name: Status
          type: string
        - description: |-
            CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.
            Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
          jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
      name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
    - additionalPrinterColumns:
        - description: Current status of the machine.
          jsonPath: .status.currentStatus.phase
          name: Status
          type: string
        - description: |-
            CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.
            Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
          jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
      name: v1alpha2
      served: true
      storage: false
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}

---

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: machinesets.machine.sapcloud.io
spec:
  conversion:
    strategy: None
  group: machine.sapcloud.io
  names:
    kind: MachineSet
    listKind: MachineSetList
    plural: machinesets
    shortNames:
      - machset
    singular: machineset
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - description: Number of desired replicas.
          jsonPath: .spec.replicas
          name: Desired
          type: integer
        - description: Number of actual replicas.
          jsonPath: .status.replicas
          name: Current
          type: integer
        - description: Number of ready replicas for this machine set.
          jsonPath: .status.readyReplicas
          name: Ready
          type: integer
        - description: |-
            CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.
            Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
          jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
      name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
    - additionalPrinterColumns:
        - description: Number of desired replicas.
          jsonPath: .spec.replicas
          name: Desired
          type: integer
        - description: Number of actual replicas.
          jsonPath: .status.replicas
          name: Current
          type: integer
        - description: Number of ready replicas for this machine set.
          jsonPath: .status.readyReplicas
          name: Ready
          type: integer
        - description: |-
            CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.
            Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
          jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
      name: v1alpha2
      served: true
      storage: false
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}

---

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: machinedeployments.machine.sapcloud.io
spec:
  conversion:
    strategy: None
  group: machine.sapcloud.io
  names:
    kind: MachineDeployment
    listKind: MachineDeploymentList
    plural: machinedeployments
    shortNames:
      - machdeploy
    singular: machinedeployment
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - description: Total number of ready machines targeted by this machine deployment.
          jsonPath: .status.readyReplicas
          name: Ready
          type: integer
        - description: Number of desired machines.
          jsonPath: .spec.replicas
          name: Desired
          type: integer
        - description: Total number of non-terminated machines targeted by this machine
            deployment that have the desired template spec.
          jsonPath: .status.updatedReplicas
          name: Up-to-date
          type: integer
        - description: Total number of available machines (ready for at least minReadySeconds)
            targeted by this machine deployment.
          jsonPath: .status.availableReplicas
          name: Available
          type: integer
        - description: |-
            CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.
            Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
          jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
      name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
    - additionalPrinterColumns:
        - description: Total number of ready machines targeted by this machine deployment.
          jsonPath: .status.readyReplicas
          name: Ready
          type: integer
        - description: Number of desired machines.
          jsonPath: .spec.replicas
          name: Desired
          type: integer
        - description: Total number of non-terminated machines targeted by this machine
            deployment that have the desired template spec.
          jsonPath: .status.updatedReplicas
          name: Up-to-date
          type: integer
        - description: Total number of available machines (ready for at least minReadySeconds)
            targeted by this machine deployment.
          jsonPath: .status.availableReplicas
          name: Available
          type: integer
        - description: |-
            CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.
            Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
          jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
      name: v1alpha2
      served: true
      storage: false
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}

---

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kubevirtmachineclasses.machine.sapcloud.io
spec:
  conversion:
    strategy: None
  group: machine.sapcloud.io
  names:
    kind: KubevirtMachineClass
    listKind: KubevirtMachineClassList
    plural: kubevirtmachineclasses
    shortNames:
      - kubevirtcls
    singular: kubevirtmachineclass
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - jsonPath: .spec.pvcSize
          name: PVC Size
          type: string
        - jsonPath: .spec.cpus
          name: CPUS
          type: string
        - jsonPath: .spec.storageClassName
          name: Storage Class Name
          type: string
        - jsonPath: .spec.memory
          name: Memory
          type: string
        - jsonPath: .spec.namespace
          name: Namespace
          type: string
        - jsonPath: .spec.sourceURL
          name: Source URL
          type: string
        - jsonPath: .spec.dnsConfig
          name: DNS Config
          type: string
        - jsonPath: .spec.dnsPolicy
          name: DNS Policy
          type: string
        - description: |-
            CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.
            Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
          jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
      name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}